server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Babywolf1992/spring-cloud/configapplication
#          repos:
#            development:
#              pattern:
#                - */development
#              uri: https://github.com/Babywolf1992/spring-cloud/configapplication
#            distribution:
#              pattern:
#                - */distribution
#              uri: https://github.com/Babywolf1992/spring-cloud/configapplication