info:
  component: Turbine

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

turbine:
  appConfig: app1,hystrix,app2
  clusterNameExpression:  new String("default")
