info:
  component: Turbine

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5

turbine:
#  aggregator:
#      clusterConfig: HYSTRIX,APP1,APP2
  appConfig: hystrix,app1,app2
#  ConfigPropertyBasedDiscovery:
#      CLIENTSAMPLE:
#        instances: localhost:9006,localhost:9005,localhost:8080
  clusterNameExpression: new String('default')
#  clusterNameExpression: metadata['cluster']


