info:
  component: Turbine

server:
  port: 9999

management:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5

turbine:
  appConfig: hystrix,app1,app2
  clusterNameExpression: new String("default")


